import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Hero from "@/components/hero/Hero";
import Navbar from "@/components/navbar/Navbar";
import SectionCard from "@/components/card/SectionCard";
import { magic } from "@/lib/magic-client";
import {
  getAnticipatedMovie,
  getPopularMovie,
  getDisneyMovie, getGhibliMovie
} from "@/lib/tmdbCalls";

export async function getServerSideProps() {
  return {
    props: {
      popularMovie: await getPopularMovie(),
      anticipatedMovie: await getAnticipatedMovie(),
      disneyMovie: await getDisneyMovie(),
      ghibliMovie: await getGhibliMovie(),
    },
  };
}
export default function Home({popularMovie, anticipatedMovie, disneyMovie, ghibliMovie }) {
  return (
    <>
      <Head>
        <title>Nextflux</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className={styles.main}>
        <Navbar />
        <Hero
          id="116135"
          title="Vikings Valhalla"
          subTitle="a very cute dog"
          imgUrl="/assets/hero-img.jpg"
        />
        <div className={styles.sectionWrapper}>
          <SectionCard
            title="Popular Movie"
            videos={popularMovie}
            size="large"
          /><SectionCard
            title="Disney Movie"
            videos={disneyMovie}
            size="medium"
          /><SectionCard
            title="Ghibli Movie"
            videos={ghibliMovie}
            size="medium"
          />
          <SectionCard
            title="Anticipated Movie"
            videos={anticipatedMovie}
            size="large"
          />
        </div>
      </div>
    </>
  );
}
